base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home_view, name='home'),
]

spider_network/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('base.urls', namespace='spider_network')),
]

base/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

import nmap # nework mapper
import socket 
import fcntl
import struct


# Create your views here.

# This function gets the ip address without using external python package
def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

def home_view(request):
    template = 'body/home.html'
    context = {} # python dictionary to be sent to the template
    
    nm = nmap.PortScanner() 
    host_ip_address =  get_ip_address('wlp3s0') # current host ip addess. wlp should change depending on os 
    
    context['host_ip_address'] = host_ip_address
    
    hosts_data = nm.scan(hosts= host_ip_address + "/24" , arguments="-sP")
    host_list = (host for host in hosts_data['scan'])
    context['host_list'] = host_list
    return render(request, template, context)
    

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Spider Network</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
	</head>

	<body>
		<div id="logo">
			<h2></h2>
		</div>
		
		<div id="menu">
			<ul class="nav nav-pills">
				<li class="active"><a href="{% url 'spider_network:home' %}" title="">Home</a></li>
				<li><a href="#" title="">Network</a></li>
				<li><a href="#" title="">Instructions</a></li>
				
				<!--<li><a href="instructions.php" accesskey="2" title="">Instructions</a></li>
				<li><a href="about.php" accesskey="4" title="">About</a></li> -->
			</ul>
		</div>
		<hr />
		
		{% block content %} {% endblock %}
	</body>
</html>

base/templates/body/home.html
{% extends "base/base.html" %}

{% block content %}
  <div id="page">
    <!-- start content -->
    <div id="content">
      <div class="post">
      <div class="container-fluid bg-1 text-center">
        <div class="jumbotron ">
        <h1>Device Inventory</h1> 
        <p>List of all devices found on network</p> 
        </div>
      </div>
      
        <div class="entry">
          <div class="btn-group" role="group" aria-label="...">
            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span></button>
            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></span></button>
            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-download-alt"></span></button>
          </div>
          <table class="table table-bordered"><tr>
          <td width='150'><b>Device Name</b></td>
          <td width='100'><b>Brand</b></td>
          <td width='150'><b>Model</b></td>
          <td width='150'><b>Serial</b></td>
          <td width='100'><b>IP Address</b></td>
          <td width='100'><b>MAC Address</b></td>
          
          </table>
          
          
        </div>
        <p class="meta">Total Found &nbsp;|&nbsp;  Devices</p>
      </div>
      
    </div>
    <!-- end content -->

  </div>
  <!-- end page -->
{% endblock %}